authors = ["Andrey Stepnov <a.stepnov@geophystech.ru>"]
name = "GroundMotion"
uuid = "787fd7a8-e7e3-4b59-bc4b-43f0e4bfbf20"
license = "Apache License 2.0"

[deps]
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Geodesy = "1.0.1"
julia = "1.5"


