name = "GroundMotion"
uuid = "787fd7a8-e7e3-4b59-bc4b-43f0e4bfbf20"
license = "Apache License 2.0"
authors = ["Andrey Stepnov <a.stepnov@geophystech.ru>"]
version = "0.4.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
