name = "GroundMotion"
uuid = "1a1bcaad-b889-5540-93fc-02c6735e0f5a"
license = "Apache License 2.0"
authors = ["Andrey Stepnov <a.stepnov@geophystech.ru>"]
version = "0.4.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
Geodesy = "1.1.0"
DelimitedFiles = "1.9.1"
